### ISSUE TITLE
AttributeError: module 'gnuradio.*_module' has no attribute '*'

### ISSUE THREAD

**Issue by Vincenque** [Vincenque/gr-add_tag_module#2]
While Executing: /usr/bin/python3 -u /home/witek/Desktop/gr-add_tag_module/testTagModule.py
```
Traceback (most recent call last):
  File "/home/witek/Desktop/gr-add_tag_module/testTagModule.py", line 180, in <module>
    main()
  File "/home/witek/Desktop/gr-add_tag_module/testTagModule.py", line 158, in main
    tb = top_block_cls()
  File "/home/witek/Desktop/gr-add_tag_module/testTagModule.py", line 99, in __init__
    self.add_tag_module_add_tag_0 = add_tag_module.add_tag(True)
AttributeError: module 'gnuradio.add_tag_module' has no attribute 'add_tag'

>>> Done (return code 1)
```

**Comment by Vincenque** [comment]
Resolved in commit: aeb8f70f0c5178c2479d1539c215ee4904e4c9ce

Not sure if it is a the best possible fix, but did some kind of workaround:
I have edited file /usr/local/lib/python3.10/dist-packages/gnuradio/add_tag_module/__init__.py from (need to be done after every build/rebuild):
```
import os
try:
    from .add_tag_module_python import *
except ModuleNotFoundError:
    pass
```
to:
```
import os
try:
    from add_tag_module.add_tag_module_python import *
except ModuleNotFoundError:
    pass
```
